spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:${RDS_PORT:3306}/${DATABASE_NAME:treaxure}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081

# 로깅 설정
logging:
  level:
    root: INFO
    com.trip.treaxure: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO 