name: Feature request
description: Suggest or plan a new feature
labels: [feat]

body:
  - type: markdown
    attributes:
      value: |
        👇 Please describe the feature you'd favorite to implement.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: e.g. Add delay time display when target time is exceeded
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: Todo
      placeholder: |
        - [ ] Implement core logic
        - [ ] Update badge text
        - [ ] Write tests
        - [ ] Update documentation
    validations:
      required: false

  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: Additional notes, concerns, or links
      placeholder: Anything else worth noting?